export interface TbUsuarioDto {
  idUsuario?: number | null;
  nomUsuario?: String | null;
  apPaternoUsuario?: String | null;
  apMaternoUsuario?: String | null;
  nroDniUsuario?: String | null;
  fchNacimeintoUsuario?: String | null;
  sexo?: String | null;
  idPerfil?: number | null;
  tipousuario?: String | null;
  codPerfil?: String | null;
  detalle?: String | null;
  idDetalle?: number | null;
  copiDni?: String | null;
  copiPartidaNacimiento?: String | null;
  foto?: String | null;
  idContacto?: number | null;
  nroTelefono?: String | null;
  tipoOperador?: String | null;
  codOperador?: String | null;
  correo?: String | null;
  idApoderado?: number | null;
  nomApoderado?: String | null;
  apPaternoApoderado?: String | null;
  apMaternoApoderado?: String | null;
  nroDniApoderado?: String | null;
  telefonoApooderado?: String | null;
  codOperadorApoderado?: String | null;
  direccion?: String | null;
  certEstudio?: String | null;
  idCurso?: number | null
  idCursos?: any | null
}
